import React from 'react';

function Database () {
    let valor = {
        basecomentarios: [
            {comentarios: [{nome: "joao", comentario: "legal", avaliacao: 5}, {nome: "maria", comentario: "muito bom", avaliacao: 5}, {nome: "carlos", comentario: "mais ou menos", avaliacao: 3} ]}
        
        ],
        baseusuarios: [
            {img:"link", titulo:"Mario Fernandes Arquiteto (0)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Antunes Arquitetura(1)", desc:"sou um arquiteto de MANAUS", classif:4, cidade:"MANAUS"},
            {img:"link", titulo:"Cabral Melo Arquitetos(2)", desc:"sou um arquiteto de SALVADOR", classif:4, cidade:"SALVADOR"},
            {img:"link", titulo:"João Roberto Pereira(3)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Carlos Rafael de Sousa(4)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Wellington paiva dos santos(5)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Onesvaldo pereira robertson(6)", desc:"sou um arquiteto de SALVADOR", classif:4, cidade:"SALVADOR"},
            {img:"link", titulo:"homer simpson(7)", desc:"sou um arquiteto de CAMPO GRANDE", classif:4, cidade:"CAMPO GRANDE"},
            {img:"link", titulo:"Thor o grande(8)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Wescley Weslley Wiskas(9)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Omar le Petit de Buffet(10)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Mariana Braga Arquiteta e Urbanista(11)", desc:"sou um arquiteto de BELO HORIZONTE", classif:4, cidade:"BELO HORIZONTE"},
            {img:"link", titulo:"Mariana Braga Arquiteta e Urbanista(12)", desc:"sou um arquiteto de BELO HORIZONTE", classif:4, cidade:"BELO HORIZONTE"},
            {img:"link", titulo:"Mariana Braga Arquiteta e Urbanista(13)", desc:"sou um arquiteto de CURITIBA", classif:4, cidade:"CURITIBA"},
            {img:"link", titulo:"Mariana Braga Arquiteta e Urbanista(14)", desc:"sou um arquiteto de RECIFE", classif:4, cidade:"RECIFE"},
            {img:"link", titulo:"Mariana Braga Arquiteta e Urbanista(15)", desc:"sou um arquiteto de RECIFE", classif:4, cidade:"RECIFE"},
            {img:"link", titulo:"Mariana Braga Arquiteta e Urbanista(16)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Mariana Braga Arquiteta e Urbanista(17)", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Ednaldo weberston", desc:"sou um arquiteto de BOA VISTA", classif:4, cidade:"BOA VISTA"},
            {img:"link", titulo:"Silvio Santos", desc:"sou um arquiteto de PORTO VELHO", classif:4, cidade:"PORTO VELHO"},
            {img:"link", titulo:"Marcos Eduardo Abismo", desc:"sou um arquiteto de PORTO VELHO", classif:4, cidade:"PORTO VELHO"},
            {img:"link", titulo:"Abelardo Silveira Silvestre", desc:"sou um arquiteto de PORTO ALEGRE", classif:4, cidade:"PORTO ALEGRE"},
            {img:"link", titulo:"Rocky Balboa da Silva", desc:"sou um arquiteto de PORTO VELHO", classif:4, cidade:"PORTO VELHO"},
            {img:"link", titulo:"Marty McFly de Oliveira", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Windows Roberto de Castro", desc:"sou um arquiteto de BOA VISTA", classif:4, cidade:"BOA VISTA"},
            {img:"link", titulo:"Mario de Hasmamann", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Universo Arquitetura", desc:"sou um arquiteto de PORTO VELHO", classif:4, cidade:"PORTO VELHO"},
            {img:"link", titulo:"Flalencarlos Flambogastro", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Betina da Empiricus", desc:"sou um arquiteto de SÃO PAULO", classif:4, cidade:"SÃO PAULO"},
            {img:"link", titulo:"Marcosvaldo Pereira de Parede", desc:"sou um arquiteto de BOA VISTA", classif:4, cidade:"BOA VISTA"},
            {img:"link", titulo:"Whindersson Nunes", desc:"sou um arquiteto de PORTO ALEGRE", classif:4, cidade:"PORTO ALEGRE"},
            {img:"link", titulo:"Marquim da Marreta Arquitetura", desc:"sou um arquiteto de PORTO ALEGRE", classif:4, cidade:"PORTO ALEGRE"},
            {img:"link", titulo:"Lindomar o Subzero Brasileiro", desc:"sou um arquiteto de TERESINA", classif:4, cidade:"TERESINA"},
            {img:"link", titulo:"Jeremias Caba Home", desc:"sou um arquiteto de SÃO PAULO", classif:4, cidade:"SÃO PAULO"},
            {img:"link", titulo:"Mirosmar Microscópio Óptico", desc:"sou um arquiteto de SÃO PAULO", classif:4, cidade:"SÃO PAULO"},
            {img:"link", titulo:"Natrave Arquitetos Imprecisos", desc:"sou um arquiteto de SÃO PAULO", classif:4, cidade:"SÃO PAULO"},
            {img:"link", titulo:"NASA Arquitetura", desc:"sou um arquiteto de SÃO PAULO", classif:4, cidade:"SÃO PAULO"},
            {img:"link", titulo:"Acrosmarlisson Arquiteto", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Mariscleuda Arquiteta", desc:"sou um arquiteto de TERESINA", classif:4, cidade:"TERESINA"},
            {img:"link", titulo:"Marcas Feminino de Marcos", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Malabarismo Studio de Arquitetura", desc:"sou um arquiteto de VITÓRIA", classif:4, cidade:"VITÓRIA"},
            {img:"link", titulo:"FAZEMOS SEU PROJETO!!!", desc:"sou um arquiteto de VITÓRIA", classif:4, cidade:"VITÓRIA"},
            {img:"link", titulo:"Heliodonto Clínica de Arquitetura", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Joesley Batista Rico", desc:"sou um arquiteto de TERESINA", classif:4, cidade:"TERESINA"},
            {img:"link", titulo:"Bill Gates", desc:"sou um arquiteto de VITÓRIA", classif:4, cidade:"VITÓRIA"},
            {img:"link", titulo:"Androtops Arquitops Top", desc:"sou um arquiteto de FORTALEZA", classif:4, cidade:"FORTALEZA"},
            {img:"link", titulo:"Eurotreino treinos em arquitetura", desc:"sou um arquiteto de BOA VISTA", classif:4, cidade:"BOA VISTA"},
            {img:"link", titulo:"Pedraria Pedras", desc:"sou um arquiteto de RIO BRANCO", classif:4, cidade:"RIO BRANCO"},
            {img:"link", titulo:"Ulala Arquiteturalalala", desc:"sou um arquiteto de RIO BRANCO", classif:4, cidade:"RIO BRANCO"},
            {img:"link", titulo:"Janela Louca Estudio", desc:"sou um arquiteto de RIO BRANCO", classif:4, cidade:"RIO BRANCO"},
            {img:"link", titulo:"Hedredoscópio Tosgolo Gagaga", desc:"sou um arquiteto de RIO BRANCO", classif:4, cidade:"RIO BRANCO"},
            {img:"link", titulo:"Débora Ferreira Design", desc:"sou um arquiteto de SÃO LUÍS", classif:4, cidade:"SÃO LUÍS"},
            {img:"link", titulo:"Alice no País das Maravilhas", desc:"sou um arquiteto de SÃO LUÍS", classif:4, cidade:"SÃO LUÍS"},
            {img:"link", titulo:"Aura Design de Interiores", desc:"sou um arquiteto de SÃO LUÍS", classif:4, cidade:"SÃO LUÍS"},
            {img:"link", titulo:"Átomo Arquitetura Nuclear", desc:"sou um arquiteto de MACEIÓ", classif:4, cidade:"MACEIÓ"},
            {img:"link", titulo:"Acrísio Antunes Antoldo", desc:"sou um arquiteto de MACEIÓ", classif:4, cidade:"MACEIÓ"},
            {img:"link", titulo:"Anatólio Arquiteto e Design", desc:"sou um arquiteto de BRASÍLIA", classif:4, cidade:"BRASÍLIA"},
            {img:"link", titulo:"Angolo Adala Antulu", desc:"sou um arquiteto de BRASÍLIA", classif:4, cidade:"BRASÍLIA"},
            {img:"link", titulo:"Troposcoporo Design", desc:"sou um arquiteto de BRASÍLIA", classif:4, cidade:"BRASÍLIA"},
            {img:"link", titulo:"Regiscar Arquiteto e Mecânico", desc:"sou um arquiteto de BRASÍLIA", classif:4, cidade:"BRASÍLIA"},
            {img:"link", titulo:"Iroslildo Instalador de Antivírus", desc:"sou um arquiteto de FLORIANÓPOLIS", classif:4, cidade:"FLORIANÓPOLIS"},
            {img:"link", titulo:"Websley Arquitetura e Design", desc:"sou um arquiteto de FLORIANÓPOLIS", classif:4, cidade:"FLORIANÓPOLIS"},
            {img:"link", titulo:"Ronalda Mota Arquiteta e Urbanista", desc:"sou um arquiteto de FLORIANÓPOLIS", classif:4, cidade:"FLORIANÓPOLIS"},
            {img:"link", titulo:"Uiraporã Design de Móveis", desc:"sou um arquiteto de FLORIANÓPOLIS", classif:4, cidade:"FLORIANÓPOLIS"},
            {img:"link", titulo:"Ellie La Vaca Loca", desc:"sou um arquiteto de ARACAJU", classif:4, cidade:"ARACAJU"},
            {img:"link", titulo:"Outros Arquitetos", desc:"sou um arquiteto de ARACAJU", classif:4, cidade:"ARACAJU"},
            {img:"link", titulo:"Arquitetus Analfabetus", desc:"sou um arquiteto de ARACAJU", classif:4, cidade:"ARACAJU"},
            {img:"link", titulo:"Alira Lira de Lira", desc:"sou um arquiteto de JOÃO PESSOA", classif:4, cidade:"JOÃO PESSOA"},
            {img:"link", titulo:"Tela OLED Escritório de Arquitetura", desc:"sou um arquiteto de JOÃO PESSOA", classif:4, cidade:"JOÃO PESSOA"},
            {img:"link", titulo:"Carnaúba Supermercados: sempre no mesmo lugar!", desc:"sou um arquiteto de JOÃO PESSOA", classif:4, cidade:"JOÃO PESSOA"},
            {img:"link", titulo:"Hogwarts Estudio de Bruxaria e Design", desc:"sou um arquiteto de JOÃO PESSOA", classif:4, cidade:"JOÃO PESSOA"},
            {img:"link", titulo:"Halala Loriro Lalolo", desc:"sou um arquiteto de JOÃO PESSOA", classif:4, cidade:"JOÃO PESSOA"},
            {img:"link", titulo:"Webstlan Arquiteto Instantâneo", desc:"sou um arquiteto de BELÉM", classif:4, cidade:"BELÉM"},
            {img:"link", titulo:"Atrion Arquitetura", desc:"sou um arquiteto de BELÉM", classif:4, cidade:"BELÉM"},
            {img:"link", titulo:"Ueria Estudio de Design", desc:"sou um arquiteto de CAMPO GRANDE", classif:4, cidade:"CAMPO GRANDE"},
            {img:"link", titulo:"Macaco Louco Arquiteto do Mau", desc:"sou um arquiteto de CAMPO GRANDE", classif:4, cidade:"CAMPO GRANDE"},
            {img:"link", titulo:"Acrobacias Acrobaturas", desc:"sou um arquiteto de GOIÂNIA", classif:4, cidade:"GOIÂNIA"},
            {img:"link", titulo:"Érika Silveira Arquiteta", desc:"sou um arquiteto de GOIÂNIA", classif:4, cidade:"GOIÂNIA"},
            {img:"link", titulo:"Maria de Jesus Arquiteta", desc:"sou um arquiteto de MACAPÁ", classif:4, cidade:"MACAPÁ"},
            {img:"link", titulo:"Uirã Ubapoke Arquiteto e Designer", desc:"sou um arquiteto de NATAL", classif:4, cidade:"NATAL"},
            {img:"link", titulo:"Orion Arquitetura(18)", desc:"sou um arquiteto de RIO DE JANEIRO", classif:4, cidade:"RIO DE JANEIRO"}],
            
        
        basecidades: ["BRASIL","ARACAJU","BELÉM","BELO HORIZONTE","BOA VISTA","BRASÍLIA","CAMPO GRANDE","CUIABÁ",
        "CURITIBA","FLORIANÓPOLIS","FORTALEZA","GOIÂNIA","JOÃO PESSOA","MACAPÁ","MACEIÓ","MANAUS","NATAL",
        "PALMAS","PORTO ALEGRE","PORTO VELHO","RECIFE","RIO BRANCO","RIO DE JANEIRO","SALVADOR","SÃO LUÍS",
        "SÃO PAULO","TERESINA","VITÓRIA"],

        comentarios: [{nome: "fulano", comentario:"muito bom!", avaliacao:5}],
    }
    return valor;
}
export default Database;